FROM       centos:centos7.4.1708
MAINTAINER Hiroyuki Kemma
ENV        LANG     ja_JP.UTF-8
ENV        LANGUAGE ja_JP:ja
ENV        LC_ALL   ja_JP.UTF-8
RUN        yum install -y make
RUN        yum install -y wget
RUN        yum install -y expect
RUN        yum install -y unzip
RUN        yum install -y perl perl-Digest-MD5
RUN        yum install -y epel-release
RUN        yum install -y python-pip
RUN        pip install reportlab
RUN        pip install sphinx
RUN        pip install sphinxcontrib-actdiag sphinxcontrib-blockdiag sphinxcontrib-nwdiag sphinxcontrib-seqdiag
RUN        wget https://oscdl.ipa.go.jp/IPAfont/IPAfont00303.zip -P /tmp
RUN        unzip /tmp/IPAfont00303.zip -d /tmp
RUN        mkdir -p /usr/share/fonts/truetype/ttf-ipa-font
RUN        cp -f /tmp/IPAfont00303/ipa*.ttf /usr/share/fonts/truetype/ttf-ipa-font
    RUN        wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz -P /tmp
RUN        tar xvzf /tmp/install-tl-unx.tar.gz -C /tmp
ADD        .vimrc /root/.vimrc
ADD        expect_latex.sh /tmp
RUN        chmod 777 /tmp/expect_latex.sh
RUN        /tmp/expect_latex.sh
RUN        rm -rf /tmp/install-tl /tmp/IPAfont00303 /tmp/expect_latex.sh
